extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
root: true
rules:
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    - ignoreRestSiblings: true
      argsIgnorePattern: ^_
      varsIgnorePattern: ^[A-Z]
  comma-dangle:
    - error
    - always-multiline
  indent:
    - error
    - 4
  no-trailing-spaces:
    - error
    - ignoreComments: false
      skipBlankLines: false
  semi: 2
  quotes: [error, single]